### ISSUE TITLE
System.ArgumentOutOfRangeException: Ungültige Win32-FileTime

### ISSUE THREAD

**Issue by Lupy720** [asdfjkl/yahb#15]
Thank you for this nice piece of code!
Unfortunately, after the second run of a backup, I receive this error message after some percentages:

---
copying files: [##        ]  21%  ETR: 00:03:43
Unbehandelte Ausnahme: System.ArgumentOutOfRangeException: Ungültige Win32-FileTime.
Parametername: fileTime
   bei System.DateTime.FromFileTimeUtc(Int64 fileTime)
   bei yahb.CopyModule.doCopy()
   bei yahb.Program.Main(String[] args)
----

Unfortunately no informations about which file is affected in the log file. 

Can you help me with this?
Thank you very much in advance!

**Comment by Lupy720** [comment]
Thank you very much! Now the script prints the affected file in the log file and skips it. ❤️

**Comment by asdfjkl** [comment]
I would really like to get to the bottom of this. Could you provide the file, or check the file-stamp of the file (i.e. right-click on the file in windows explorer)? What do the time-stamps say?

**Comment by Lupy720** [comment]
Unfortunately I cannot upload it, because of private data and I guess the time stamp will be changed if I erase the data and send the file to you.
But I checked the timestamp and there seems to be the problem. Last changed: ‎Dienstag, ‎6. ‎Oktober ‎29953, ‏‎06:02:55
Dont know how this happens.

**Comment by asdfjkl** [comment]
thanks for the reply and reporting this bug. I will release a new version soon; meanwhile you can simply use the attached .exe.
