### ISSUE TITLE
Problem with R/O Files

### ISSUE THREAD

**Issue by g-user** [asdfjkl/yahb#2]
There is a problem with (incremental?) Backups. if the source file is readonly flagged.
Even with admin-right an error is generated. If on remove the readonly-flag from the source file, everything is fine:

Unbehandelte Ausnahme: System.UnauthorizedAccessException: Der Zugriff auf den Pfad "w:\BACKUP\202002182353\d__\test.pdf" wurde verweigert.
   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   bei System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   bei System.IO.File.OpenFile(String path, FileAccess access, SafeFileHandle& handle)
   bei System.IO.File.SetCreationTimeUtc(String path, DateTime creationTimeUtc)
   bei System.IO.FileSystemInfo.set_CreationTimeUtc(DateTime value)
   bei System.IO.FileSystemInfo.set_CreationTime(DateTime value)
   bei yahb.CopyModule.doCopy()
   bei yahb.Program.Main(String[] args)

**Comment by asdfjkl** [comment]
For confirmation: You can create a first backup without problems, but the second (incremental) backup fails, correct? 
After copying, yahb (re)sets the time stamp of file-creation of the target file to the value of the source file. The log looks as if this fails, as the file is read-only. I'll try to create an update soon.

**Comment by asdfjkl** [comment]
I'd be interested to know wether https://github.com/asdfjkl/yahb/releases/tag/v1.0.2 fixes your issue...

**Comment by asdfjkl** [comment]
Well I guess so...
