### ISSUE TITLE
feature request: more than one different source directory in parallel (like  rsyncbackup.vbs)

### ISSUE THREAD

**Issue by g-user** [asdfjkl/yahb#3]
It would be nice, if more than one source directory can be backuped at the same time, like in rsyncbackup.vbs:
sourceFolders = Array("BITTE TRAGEN SIE DIE QUELLPFADE IM SKRIPT EIN")

**Comment by asdfjkl** [comment]
This is already (prototypical, untested, undocumented) implemented via option /id:filename.txt where filename.txt contains a list of directories, each line one directory. /id is then passed instead of source-dir - I guess this is what you mean?!
