### ISSUE TITLE
yahb dies with "UnauthorizedAccessException"

### ISSUE THREAD

**Issue by Searle** [asdfjkl/yahb#6]
I guess the file should be skipped and the Error logged.

If you should fix this error I would be really thankful for a Win7-Release. (Would be a pity if I couldn't use this very nice solution...)

```
yahb C:\ K:\YAHB\C /vss /+log:K:\YAHB\C.log /s /x
f:*.tmp;tmp;temp
copying files: [####      ]  40%  ETR: 03:18:53
Unbehandelte Ausnahme: System.UnauthorizedAccessException: Der Zugriff auf den Pfad "C:\Users\All Users\Microsoft\Diagnosis\events00.rbs" wurde verweigert.
   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   bei yahb.CopyModule.doCopy()
   bei yahb.Program.Main(String[] args)
```

**Comment by asdfjkl** [comment]
You are using /vss. Did you execute YAHB from an elevated command prompt?

**Comment by asdfjkl** [comment]
would love to here wether https://github.com/asdfjkl/yahb/releases/tag/v1.0.6 fixes your issue.

Win7 can't handle long pathnames (cf MAX_PATH). Also won't fix any Win7 specific bugs, as I have no test machine. But aside from that, yahb should run fine on Win7.

**Comment by asdfjkl** [comment]
I guess so...
